# Generated by Django 4.1.3 on 2022-12-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_song_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.TextField(default=0),
        ),
    ]
