# Generated by Django 4.1.3 on 2023-01-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_song_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_Email', models.EmailField(max_length=254)),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
            ],
        ),
    ]
