# Generated by Django 4.1.3 on 2023-01-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='songs',
            field=models.TextField(),
        ),
    ]
