# Generated by Django 4.1.5 on 2023-01-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vote_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='mac_address',
            field=models.TextField(default=234),
            preserve_default=False,
        ),
    ]
