# Generated by Django 4.1.5 on 2023-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vote_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.TextField()),
                ('song_id', models.TextField()),
                ('user_Email', models.TextField()),
            ],
        ),
    ]
