# Generated by Django 4.1.5 on 2023-01-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='mac_address',
        ),
    ]
