# Generated by Django 4.1.6 on 2026-05-04 09:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="songs/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="song",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.models.song_directory_path,
            ),
        ),
    ]
