# Generated by Django 4.1.6 on 2026-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_song_thumbnail_alter_song_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="fallback_song_data_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="fallback_thumbnail_data_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
