# Generated by Django 4.1.6 on 2026-05-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_voterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_payments_phone",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number for paid vote confirmations (country code + number). Used for wa.me links. Edit under Administration.",
                max_length=32,
            ),
        ),
    ]
