# Generated by Django 4.1.6 on 2026-05-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_sitesettings_whatsapp_payments_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("vote_count", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="CDF", max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="afrimoney_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="airtel_money_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mpesa_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="payment_instructions_note",
            field=models.TextField(
                blank=True,
                help_text="Optional extra lines shown to buyers (e.g. business hours, fees).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="payment_registered_name",
            field=models.CharField(
                blank=True,
                help_text="Name shown on mobile money account (pay to this name).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="voterequest",
            name="currency_code",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="voterequest",
            name="price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="whatsapp_payments_phone",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp for payment screenshots / confirmation (country code + number). Used for wa.me links.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="voterequest",
            name="package",
            field=models.CharField(
                help_text="Snapshot label (from VotePackage.title)", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="voterequest",
            name="vote_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="core.votepackage",
            ),
        ),
    ]
