# Generated by Django 4.1.6 on 2026-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_vote_packages_and_payment_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="voterequest",
            name="payment_proof",
            field=models.ImageField(
                blank=True,
                help_text="Buyer screenshot / receipt (required on new requests via website form).",
                max_length=500,
                null=True,
                upload_to="vote_payment_proofs/%Y/%m/",
            ),
        ),
    ]
