# Generated by Django 4.1.6 on 2026-05-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_voterequest_payment_proof"),
    ]

    operations = [
        migrations.AddField(
            model_name="voterequest",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Which mobile-money line the buyer used (airtel_money, afrimoney, mpesa).",
                max_length=24,
            ),
        ),
    ]
