# Generated by Django 4.1.6 on 2026-05-04 08:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_artist_promo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="artist_promo_image",
            field=models.ImageField(
                blank=True,
                help_text="Leaderboard thumbnail (use image OR short promo video, not both).",
                max_length=500,
                null=True,
                upload_to=accounts.models._artist_promo_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="artist_promo_video",
            field=models.FileField(
                blank=True,
                help_text="Short promo clip for leaderboard (use video OR thumbnail image, not both).",
                max_length=500,
                null=True,
                upload_to=accounts.models._artist_promo_video_path,
            ),
        ),
    ]
